trigger:
  branches:
    include:
      - master
      - release-*

stages:
  - stage: ubuntu_latest
    displayName: 'ubuntu-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: Compile
        displayName: 'Compile'
        dependsOn: [  ]
        steps:
          - task: CmdLine@2
            inputs:
              script: './build.sh Compile'
      - job: Test
        displayName: 'Test'
        dependsOn: [ Compile ]
        steps:
          - task: CmdLine@2
            inputs:
              script: './build.sh Test'
          - task: PublishBuildArtifacts@1
            inputs:
              artifactName: test-results
              pathtoPublish: 'artifacts/test-results'
      - job: Pack
        displayName: 'Pack'
        dependsOn: [ Compile, Test ]
        steps:
          - task: CmdLine@2
            inputs:
              script: './build.sh Pack'
          - task: PublishBuildArtifacts@1
            inputs:
              artifactName: packages
              pathtoPublish: 'artifacts/packages'
      - job: Publish
        displayName: 'Publish'
        dependsOn: [ Test, Pack ]
        steps:
          - task: CmdLine@2
            inputs:
              script: './build.sh Publish'
